### ISSUE TITLE
Fix typos in Understanding Devsprints blog

### ISSUE THREAD

**Issue by kurianbenoy** [pythonindia/inpycon2019#197]
https://in.pycon.org/blog/2017/understanding-dev-sprints.html

- In the dev sprints blogpost please change the dates planned to be conducted as October 14, 15 2019.
- Deadline for submitting call for proposals is [Date].
- You can submit proposals page points to [2017 CFP page](https://in.pycon.org/cfp/dev-sprint-2017/proposals/)

**Comment by astronomersiva** [comment]
Hey @kurianbenoy, thanks for taking the time to report this issue.

I just took a look at the links and it seems like the blog post you are referring to is from the 2017 edition. That's the reason why the date shown is 2017 and tha's also why the CFP page is redirecting to the 2017 edition's proposals page.

PyCon India preserves blog posts every year and I don't think it's a good idea to update previous blog entries to point to the current edition's equivalents.

The text `Deadline for submitting call for proposals is [Date].` is obviously wrong and can be changed. It would be great if you could do that in the [blog repo](https://github.com/pythonindia/inpycon-blog). However, I am not sure what merits that would have considering that there will be almost no traffic to that page.

I am also curious as to how you ended up in such an old blog post so that we can try and ensure that all links point to the current edition only.

**Comment by kurianbenoy** [comment]
Hey @astronomersiva, I thought the blogpost is this year because seeing this year themed header in that page. I check that page: to see about what is **devsprints** for a similar event we are hosting in our college.

Do you have an updated blogpost for this year?

It may still be a good idea updating because on googling this blogpost may come on a casual search about Devsprints, as apparently this name is called only for Pycon India.

**Comment by astronomersiva** [comment]
https://in.pycon.org/blog/2019/understanding-devsprints.html - this is the blog post for this year's edition and I got this by Google Search only.

Like I said before, I don't think it is a good idea to replace dates in old blog posts. Not only is it wrong, there are clear indications of the post's authored date in page. I think that should serve as an indicator. There are also scaling issues. This is the 11th edition of PyCon India and even if there are 5 pages like these, whoever is organising this next year will have to update 5*11 + 5 = 60 pages. The year after that it will be 65 pages. 

We can probably explore some other way of indicating that a post is outdated.
