### ISSUE TITLE
Connection Is Not Secure Warning

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019#84]
When viewed on https://in.pycon.org, the browser says the connection is not secure, because parts of the website were downloaded unencrypted. I am not able to figure out why. But we will need to fix that when we open up tickets.

**Comment by Sayak9495** [comment]
Hi @bravegnu , I did some digging up and found this website [whynopadlock](https://www.whynopadlock.com) and running the tests it got these [results](https://www.whynopadlock.com/results/cabade34-9638-40f0-94b3-c34fd62d61d3). So apparently there is some http issue while loading speakers images in the blogs. 
I don't know exactly but I presume it has to do something with inpycon-blog repo?

**Comment by astronomersiva** [comment]
I have raised a [PR](https://github.com/pythonindia/inpycon-blog/pull/208/files) to address this. When we construct the blog feed, we create fake DOM elements to strip HTML tags. The summary tags of keynote speaker announcement posts have `img` tags in them that trigger the loading of images. Pelican's configuration has `http://in.pycon.org` instead of the secure url which causes all hrefs in the xml to be insecure.

**Comment by bravegnu** [comment]
Thanks @Sayak9495 for helping out!
